export const WORDS = [
  "Banana", "Avião", "Hospital", "Escola", "Carro", "Pizza", "Praia", "Médico",
  "Computador", "Cachorro", "Gato", "Futebol", "Cinema", "Restaurante", "Parque",
  "Bicicleta", "Telefone", "Relógio", "Livro", "Música", "Televisão", "Internet",
  "Astronauta", "Dinossauro", "Pirata", "Castelo", "Dragão", "Super-herói",
  "Vampiro", "Zumbi", "Robô", "Espaço", "Oceano", "Deserto", "Floresta", "Montanha",
  "Cachoeira", "Vulcão", "Terremoto", "Tempestade", "Arco-íris", "Eclipse", "Cometa",
  "Galáxia", "Universo", "Microscópio", "Telescópio", "Laboratório", "Experiência",
  "Química", "Física", "Biologia", "Matemática", "História", "Geografia", "Arte",
  "Literatura", "Filosofia", "Psicologia", "Sociologia", "Economia", "Política",
  "Direito", "Medicina", "Engenharia", "Arquitetura", "Design", "Moda", "Culinária",
  "Abacaxi", "Abelha", "Acampamento", "Açougue", "Advogado", "Aeroporto", "Agulha",
  "Alface", "Almofada", "Ambulância", "Aniversário", "Apartamento", "Aquário",
  "Aranha", "Armário", "Árvore", "Aspargo", "Azeitona", "Bacalhau", "Balança",
  "Balão", "Bambolê", "Bandeira", "Banheiro", "Baralho", "Barata", "Barba",
  "Barco", "Barraca", "Batom", "Bateria", "Baú", "Beija-flor", "Berço",
  "Besouro", "Beterraba", "Biblioteca", "Bilhete", "Binóculo", "Biscoito",
  "Bisturi", "Blusa", "Bobina", "Boca", "Bode", "Boi", "Bola", "Bolacha",
  "Bolo", "Bolsa", "Bomba", "Bombeiro", "Boneca", "Boné", "Borracha", "Botão",
  "Bota", "Bracelete", "Brinquedo", "Broa", "Brócolis", "Bússola", "Cabide",
  "Cachimbo", "Cadeira", "Caderno", "Café", "Cajueiro", "Calça", "Calculadora",
  "Caleidoscópio", "Calendário", "Cama", "Camaleão", "Camarão", "Caminhão",
  "Camiseta", "Campainha", "Canário", "Caneta", "Canguru", "Canivete", "Canoa",
  "Capa", "Capacete", "Capivara", "Caracol", "Caranguejo", "Cardápio", "Carneiro",
  "Carrossel", "Carta", "Carteira", "Cartão", "Carvão", "Casa", "Casaco",
  "Cascata", "Castanha", "Cavalo", "Cebola", "Cenoura", "Cerca", "Cereja",
  "Cerveja", "Cesto", "Céu", "Chá", "Chafariz", "Chaleira", "Chaminé", "Champanhe",
  "Chapéu", "Chave", "Chicote", "Chimpanzé", "Chinelo", "Chocolate", "Chupeta",
  "Churrasco", "Chuveiro", "Cigarra", "Cinto", "Cinzeiro", "Circo", "Cisne",
  "Cofre", "Cogumelo", "Colar", "Colchão", "Colete", "Colher", "Colmeia",
  "Coluna", "Colchão", "Compasso", "Concha", "Cone", "Confete", "Coração",
  "Corda", "Cordão", "Coroa", "Corpo", "Correio", "Corrente", "Cortina",
  "Coruja", "Couve", "Cozinha", "Cravo", "Creme", "Criança", "Cristal",
  "Cruz", "Cueca", "Cuíca", "Cúpula", "Curativo", "Dado", "Damasco", "Dardo",
  "Dedo", "Degrau", "Dente", "Dentista", "Depósito", "Despertador", "Detergente",
  "Diamante", "Diário", "Dicionário", "Dinheiro", "Disco", "Dobradiça", "Doce",
  "Dominó", "Ducha", "Duende", "Dúvida", "Edifício", "Eletricista", "Elefante",
  "Elevador", "Elmo", "Envelope", "Enxada", "Escada", "Escova", "Escudo",
  "Esmalte", "Espada", "Espelho", "Espinafre", "Esponja", "Esquilo", "Estátua",
  "Esteira", "Estojo", "Estrela", "Etiqueta", "Exame", "Extintor", "Faca",
  "Fada", "Falcão", "Farol", "Farinha", "Farmácia", "Fatia", "Fechadura",
  "Feijão", "Feira", "Ferramenta", "Ferro", "Festa", "Fivela", "Flamingo",
  "Flauta", "Flecha", "Flor", "Foguete", "Folha", "Formiga", "Forno", "Forte",
  "Fósforo", "Foto", "Frango", "Frasco", "Freio", "Frigideira", "Fruta",
  "Fubá", "Fumaça", "Funil", "Furadeira", "Fusível", "Gaiola", "Gaita",
  "Galinha", "Galo", "Gancho", "Garfo", "Gargalo", "Garrafa", "Gato",
  "Gaveta", "Gelo", "Geladeira", "Gema", "Gengibre", "Gesso", "Girafa",
  "Girassol", "Globo", "Goiaba", "Gola", "Golfinho", "Goma", "Gongo",
  "Gorila", "Gorro", "Gota", "Grade", "Grampo", "Gravata", "Grelha",
  "Grilo", "Gruta", "Guarda-chuva", "Guardanapo", "Guaxinim", "Guindaste",
  "Guitarra", "Hélice", "Helicóptero", "Hiena", "Hino", "Hipopótamo",
  "Holofote", "Horta", "Hotel", "Iate", "Igreja", "Iguana", "Ímã",
  "Impressora", "Incenso", "Ingresso", "Injeção", "Inseto", "Iogurte",
  "Ioiô", "Isqueiro", "Jabuti", "Jacaré", "Janela", "Jardim", "Jarra",
  "Jasmim", "Jaula", "Jeans", "Jegue", "Joalheiro", "Joaninha", "Joelho",
  "Jogo", "Joia", "Jornal", "Juiz", "Jumento", "Junta", "Lã",
  "Lábio", "Laço", "Lacre", "Ladeira", "Ladrilho", "Lagarta", "Lagartixa",
  "Lago", "Lagoa", "Lagosta", "Lama", "Lâmpada", "Lampião", "Lança",
  "Lanche", "Lancha", "Lápis", "Laranja", "Lareira", "Lata", "Latão",
  "Leão", "Legume", "Leite", "Leme", "Lenço", "Lençol", "Lente",
  "Lentilha", "Leopardo", "Lixa", "Lixeira", "Lobo", "Locomotiva", "Loja",
  "Lona", "Lontra", "Lousa", "Louva-a-deus", "Luva", "Luz", "Maçã",
  "Macaco", "Macarrão", "Machado", "Madeira", "Madrinha", "Mágica", "Magreza",
  "Maio", "Maiô", "Mala", "Maleta", "Mamadeira", "Mamão", "Mamute",
  "Manada", "Manga", "Mangueira", "Manivela", "Manto", "Mão", "Mapa",
  "Máquina", "Mar", "Maracujá", "Marreta", "Martelo", "Máscara", "Massagem",
  "Mastro", "Matriz", "Meada", "Medalha", "Meia", "Mel", "Melancia",
  "Melão", "Mesa", "Metrô", "Microfone", "Milho", "Mimo", "Minhoca",
  "Míssil", "Mochila", "Moeda", "Moinho", "Mola", "Molde", "Molho",
  "Monitor", "Montanha", "Morango", "Morcego", "Morsa", "Mosca", "Mosquito",
  "Motor", "Móvel", "Muleta", "Muro", "Museu", "Nabo", "Nadadeira",
  "Naja", "Narguilé", "Nariz", "Navio", "Neblina", "Nectarina", "Ninho",
  "Noite", "Noiva", "Noivo", "Novelo", "Nuvem", "Óculos", "Ouriço",
  "Ouro", "Ovelha", "Ovo", "Pá", "Pacote", "Padaria", "Padrinho",
  "Pagode", "Pai", "Painel", "Palácio", "Palhaço", "Palito", "Palma",
  "Palmeira", "Panda", "Panela", "Pano", "Pantufa", "Pão", "Papagaio",
  "Papel", "Papai Noel", "Parafuso", "Paraquedas", "Parque", "Passarinho",
  "Passaporte", "Pasta", "Pastilha", "Pato", "Patins", "Pau", "Pé",
  "Pedra", "Peixe", "Pente", "Pera", "Perna", "Peruca", "Pêssego",
  "Pia", "Piano", "Picareta", "Picolé", "Pijama", "Pilha", "Pimenta",
  "Pincel", "Pinguim", "Pintura", "Pinça", "Pipa", "Pirâmide", "Pires",
  "Piscina", "Pistola", "Pivô", "Placa", "Planta", "Plástico", "Pluma",
  "Pneu", "Pó", "Poço", "Polegar", "Polícia", "Poltrona", "Polvo",
  "Pombo", "Ponte", "Porco", "Porta", "Portão", "Pote", "Prato",
  "Prateleira", "Prédio", "Prego", "Presente", "Presépio", "Pudim", "Pulseira",
  "Puma", "Puxador", "Quadro", "Queijo", "Quepe", "Quiabo", "Quibe",
  "Quimono", "Quindim", "Quintal", "Rã", "Rabanete", "Rádio", "Raio",
  "Raiz", "Raquete", "Rato", "Ratoeira", "Rede", "Régua", "Relógio",
  "Remo", "Repolho", "Revista", "Rinoceronte", "Rio", "Roda", "Rodapé",
  "Rolha", "Rolo", "Rosa", "Rosca", "Roupa", "Rua", "Sabão", "Sabonete",
  "Saco", "Sacola", "Sacolão", "Sal", "Sala", "Salada", "Salsicha",
  "Salto", "Sandália", "Sanduíche", "Sanguessuga", "Sapato", "Sapo",
  "Sardinha", "Sela", "Selo", "Semáforo", "Seringa", "Serpente", "Serra",
  "Serrote", "Sexta", "Sino", "Sirene", "Sofá", "Sol", "Soldado",
  "Sombrero", "Sorvete", "Sino", "Sutiã", "Tábua", "Tabuleiro", "Taça",
  "Tacho", "Tamanco", "Tambor", "Tampa", "Tanque", "Tapete", "Tartaruga",
  "Tatu", "Teclado", "Teia", "Telha", "Telhado", "Tênis", "Tenda",
  "Termômetro", "Tesoura", "Tigela", "Tigre", "Tijolo", "Tinta", "Tira",
  "Toalha", "Toca", "Tocha", "Tomada", "Tomate", "Torneira", "Torrada",
  "Torre", "Tortilha", "Trator", "Trem", "Trevo", "Trident", "Trigo",
  "Trilho", "Troféu", "Tromba", "Trompete", "Tronco", "Trono", "Tubarão",
  "Tubo", "Tucano", "Tulipa", "Túnel", "Turbina", "Urso", "Urubu",
  "Uva", "Vaca", "Vaga-lume", "Vagão", "Vara", "Varal", "Vaso",
  "Vassoura", "Vela", "Velocípede", "Ventilador", "Vento", "Verdura",
  "Verme", "Verruma", "Vespa", "Vestido", "Véu", "Vidro", "Viola",
  "Violão", "Violino", "Violoncelo", "Viseira", "Vitrine", "Vovó",
  "Vovô", "Xadrez", "Xale", "Xampu", "Xarope", "Xícara",
  "Xilofone", "Zebra", "Zíper", "Zoológico"
];
